courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_detail, name='text'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail, name='quiz'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create, name='create_quiz'),
    url(r'(?P<course_pk>\d+)/edit_quiz(?P<quiz_pk>\d+)/$', views.quiz_edit, name='edit_quiz'),
    url(r'(?P<quiz_pk>\d+)/create_question(?P<question_type>mc|tf)/$', views.create_question, name='create_question'),
    url(r'(?P<quiz_pk>\d+)/edit_question(?P<question_pk>\d+)/$', views.edit_question, name='edit_question'),
    url(r'(?P<question_pk>\d+)/create_answer/$', views.answer_form, name='create_answer'),
    url(r'by/(?P<teacher>[-\w]+)/$', views.courses_by_teacher, name='by_teacher'),
    url(r'search/$', views.search, name='search'), 
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^api/v1/courses', include('courses.api_urls', namespace='courses_api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^suggest/$', views.suggestion_view, name='suggestion'),
    url(r'^$', views.home_page, name='home'),
    url(r'^about-us$', views.aboutus_view, name='about_us'),
    url(r'^blog$', views.blog_view, name='blog'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    teacher = models.ForeignKey(User)
    subject = models.CharField(default='', max_length=100)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)

    class Meta:
        abstract = True
        ordering = ['order',]
    def __str__(self):
        return self.title

class Text(Step):
    content = models.TextField(blank=True, default='')

    def get_absolute_url(self):
        return reverse('courses:text', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id
        })

class Quiz(Step):
    total_questions = models.IntegerField(default=4)
    times_taken = models.IntegerField(default=0, editable=False)

    class Meta:
        verbose_name_plural = "Quizzes"

    def get_absolute_url(self):
        return reverse('courses:quiz', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id
        })

class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order',]

    def get_absolute_url(self):
        return self.quiz.get_absolute_url

    def __str__(self):
        return self.prompt

class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)

    # def get_absolute_url(self):
    #     return reverse('courses:')

class TrueFalseQuestion(Question):
    pass

class Answer(models.Model):
    question = models.ForeignKey(Question)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order',]
    
    def __str__(self):
        return self.text

courses/forms.py
from django import forms

from . import models

class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields =[
            'title',
            'description',
            'order',
            'total_questions',
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control z-depth-1 title'})
        self.fields['description'].widget.attrs.update({'class': 'form-control z-depth-1 description'})
        self.fields['order'].widget.attrs.update({'class': 'form-control z-depth-1 order'})
        self.fields['total_questions'].widget.attrs.update({'class': 'form-control z-depth-1 questions'})


class QuestionForm(forms.ModelForm):
    class Media:
        css = {'all': ('courses/css/order.css',)}
        js = (
            'courses/js/vendor/jquery.fn.sortable.min.js',
            'courses/js/order.js'
        )

class TrueFalseQuestionForm(QuestionForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = ['order', 'prompt']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['prompt'].widget.attrs.update({'class': 'form-control z-depth-1 prompt ','rows':'2'})
        self.fields['order'].widget.attrs.update({'class': 'form-control z-depth-1 order'})
        
class MultipleChoiceQuestionForm(QuestionForm):
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = [
            'prompt',
            'shuffle_answers',
            'order'
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order'].widget.attrs.update({'class': 'form-control z-depth-1 order'})
        self.fields['prompt'].widget.attrs.update({'class': 'form-control z-depth-1 prompt ','rows':'2'})
        self.fields['shuffle_answers'].widget.attrs.update({'class': 'form-control z-depth-1 shuffle_answers'})

class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields= [
            'order',
            'text',
            'correct'
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order'].widget.attrs.update({'class': 'form-control z-depth-1 order'})
        self.fields['text'].widget.attrs.update({'class': 'form-control z-depth-1 text'})
        self.fields['correct'].widget.attrs.update({'class': 'form-control z-depth-1 correct'})

AnswerFormSet = forms.modelformset_factory(
    models.Answer,
    form=AnswerForm
)

AnswerInlineFormSet = forms.inlineformset_factory(
    models.Question,
    models.Answer,
    extra=2,
    fields=('order', 'text', 'correct'),
    formset=AnswerFormSet,
    min_num=1
)

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.db.models import Q


from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response


from itertools import chain


from . import models
from . import forms
from . import serializers
# Create your views here.

def course_list(request):
    courses = models.Course.objects.filter(published=True)
    email = 'questions@learning_site.com'
    return render(request, 'courses/course_list.html', {'courses': courses, 'email':email})

def course_detail(request, pk):
    course = get_object_or_404(models.Course,pk=pk, published=True)
    try:
        course = models.Course.objects.prefetch_related(
            'quiz_set', 'text_set', 'quiz_set__question_set'
        ).get(pk=pk, published=True)
    except models.Course.DoesNotExist:
        raise Http404
    else:
        steps = sorted(chain(
            course.text_set.all(),
            course.quiz_set.all()
            ),key=lambda step: step.order)
    return render(request, 'courses/course_detail.html',{'course': course, 'steps': steps})

def text_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Text, course_id=course_pk, pk=step_pk, course__published=True)
    return render(request, 'courses/text_detail.html',{'step': step})

def quiz_detail(request, course_pk, step_pk):
    try:
        step = models.Quiz.objects.select_related('course').get(
            course_id=course_pk, pk=step_pk, course__published=True
        )
    except models.Quiz.DoesNotExist:
        raise Http404
    else:
        return render(request, 'courses/quiz_detail.html',{'step': step})

# @login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course, pk=course_pk, published=True)
    form = forms.QuizForm()

    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS, "Quiz Added")
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form})

# @login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk, course_id=course_pk, course__published=True)
    form = forms.QuizForm(instance=quiz)
    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz,data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Updated {}'.format(form.cleaned_data['title']))
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form})

# @login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk, course__published=True)
    if question_type == 'tf':
        form_class = forms.TrueFalseQuestionForm
    else:
        form_class = forms.MultipleChoiceQuestionForm
    
    form = form_class()
    answer_forms = forms.AnswerInlineFormSet(queryset=models.Answer.objects.none())

    if request.method == 'POST':
        form = form_class(request.POST)
        answer_forms = forms.AnswerInlineFormSet(request.POST,queryset=models.Answer.objects.none())

        if form.is_valid() and answer_forms.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question =question
                answer.save()
            messages.success(request, "Added question")
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/question_form.html',{
            'quiz': quiz,
            'form': form,
            'formset': answer_forms,
            })

# @login_required
def edit_question(request, quiz_pk, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk, quiz_id=quiz_pk)
    if hasattr(question, 'truefalsequestion'):
        form_class = forms.TrueFalseQuestionForm
        question = question.truefalsequestion
    else:
        form_class = forms.MultipleChoiceQuestionForm
        question = question.multiplechoicequestion
    form = form_class(instance=question)
    answer_forms = forms.AnswerInlineFormSet(queryset=form.instance.answer_set.all())

    if request.method == 'POST':
        form = form_class(request.POST, instance=question)
        answer_forms = forms.AnswerInlineFormSet(request.POST,queryset=form.instance.answer_set.all())
        if form.is_valid() and answer_forms.is_valid():
            form.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, "Updated question")
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/question_form.html', {'form': form, 'quiz': question.quiz,'formset': answer_forms,})


# @login_required
def answer_form(request, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk)
    formset = forms.AnswerFormSet(queryset=question.answer_set.all())

    if request.method == 'POST':
        formset = forms.AswerFormSet(request.POST, queryset=question.answer_set.all())

        if formset.is_valid():
            answers = formset.save(commit=False)
            for answer in answers:
                answer.question=question
                answer.save()
        messages.success(request, "Added answers")
        return HttpReponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/answer_form.html', {'question': question, 'formset': formset})


def courses_by_teacher(request, teacher):
    courses = models.Course.objects.filter(teacher__username=teacher, published=True)
    return render(request, 'courses/course_list.html', {'courses': courses})

def search(request):
    term = request.GET.get('q')
    courses = models.Course.objects.filter(
            Q(title__icontains=term)|Q(description__icontains=term),
            published=True 
        )
    return render(request, 'courses/course_list.html', {'courses': courses})


#API views start here
class ListCreateCourse(generics.ListCreateAPIView):
    queryset = models.Course.objects.all()
    serializer_class = serializers.CourseSerializer

class RetrieveUpdateDestroyCourse(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Course.objects.all()
    serializer_class = serializers.CourseSerializer

courses/templates/courses/answer_form.html
{%  extends "layout.html" %}
{% load course_extras %}

{% block title %} question | {{ question.prompt }} | {{ question.quiz.course.title }}{{block.super}} {% endblock %}

<li><a href="{% url 'courses:detail' pk=quiz.course.pk %}">{{ question.quiz.course.title }}</a></li>
<li><a href="{% url 'courses:quiz' course_pk=quiz.course.pk step_pk=quiz.pk%}">{{ question.quiz.title }}</a></li>

{% block content %}
    <div>    
        <h1>Answers</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ formset }}
            <input type="submit" value="save">
        </form>
    </div>
{% endblock %}

courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block static %}

<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}
{% load humanize %}

{% block title %} {{ course.title }} {% endblock %}

{% block content %}
<div class="container" id="courselist-container">
    <div class="row">
        <div class="col-md-6">
                {% for step in steps %}
            <a class="card-box" href="{{step.get_absolute_url }}">
                {% if step.question_set %}
                <div class="card-progress-quizz">
                        <i class="far fa-file-code fa-lg"></i>
                </div>
                <p class="card-type">Quiz</p>
                {% else %}
                <div class="card-progress">
                        <i class="fas fa-book-open fa-lg"></i>
                </div>
                <p class="card-type">Course</p>
                {% endif %}
                <h3 class="card-title">{{step.title}}</h3>
                {% if step.description|wordcount <= 5 %}
                <p class="card-description">{{step.description}}</p>
                            {% else %}
                            <p class="card-description">{{step.description|truncatewords:12}}</p>
                {% endif %}
                
            </a>            
            <div class="card-actions container">
                <div class="row" id="card-actions-container">
                    <div class="card-action secondary-action">
                        <a href="{% url 'courses:detail' pk=course.pk %}" class="button secondary">{{ course.subject }}</a>
                    </div>
                </div>
                {% if step.question_set.all %}
                <div class="questions-total">
                        
                        <span>Total Questions</span>
                        <span>{{ step.question_set.count }}</span>
                           
                </div>
                {% elif not step.question_set %}
                <div class="quizz">
                        
                        <a href="{% url 'courses:create_quiz' course_pk=course.id %}">New Quiz</a>
        
                        
                </div> 
                {% endif %}
                        
            </div>
            {% endfor %}
        </div>
        <div class="col-md-6">
                
                <a class="card-box-detail-page" href="{% url 'courses:detail' pk=course.pk %}">
                        <p class="card-type">Track</p>
                        <h3 class="card-title">Exploring {{course.title}}</h3>
                        {% if course.description %}
                        <p class="card-description">{{course.description}}</p>
                        {% endif %}
                    </a>
                    <div class="card-actions container">
                        <div class="row" id="card-actions-container">
                                <div class="card-action secondary card-action-trailer">
                                        <a href="#" data-toggle="tooltip" data-placement="top"
                                            title="For video content!">
                                            <i class="far fa-play-circle fa-2x"></i>
                                        </a>
                                </div>
                                <div class="card-action secondary" data-toggle="tooltip" data-placement="top"
                                        title="Average skill networth">
                                        <i class="fas fa-money-check-alt fa-2x"></i>
                                </div>
                                <div class="card-action secondary" data-toggle="tooltip" data-placement="top"
                                        title="Include major companies using this technology">
                                        <i class="far fa-building fa-2x"></i>
                                </div>
                        </div>
                    </div>
        </div>
    </div>
</div>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block static %}

<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}

{% block content %}
<div class="container" id="courselist-container">
    <div class="row">
        <div class="course-list-intro container-fluid">
            <hr>
            <h5>Browse Tracks</h5>
            <p>Some of the most popular courses students start with</p>
        </div>

    </div>
    <div class="row">
        {% for course in courses %}
        <div class="col-md-4">
            <a class="card-box" href="{% url 'courses:detail' pk=course.pk %}">
                <div class="card-progress">
                    <i class="fas fa-code"></i>
                    Created on: {{ course.created_at|date:"F j, Y" }}
                </div>
                <p class="card-type">Track</p>
                <h3 class="card-title">{{course.title}}</h3>
                {% if course.description|wordcount <= 5 %}
                <p class="card-description">{{course.description}</p>
                {% else %}
                <p class="card-description">{{course.description|truncatewords:12}}</p>
                {% endif %}
            </a>
            <div class="card-actions container">
                <div class="row" id="card-actions-container">
                        <div class="card-action secondary-action">
                                <a href="{% url 'courses:detail' pk=course.pk %}" class="button secondary">Explore</a>
                        </div>
                        <div class="card-action secondary card-action-trailer">
                                <a href="#" data-toggle="tooltip" data-placement="top"
                                    title="Tooltip on top">
                                    <i class="far fa-play-circle fa-2x"></i>
                                </a>
                        </div>
                        <div class="card-action secondary" data-toggle="tooltip" data-placement="top"
                                title="Tooltip on top">
                                <i class="fas fa-money-check-alt fa-2x"></i>
                        </div>
                        <div class="card-action secondary" data-toggle="tooltip" data-placement="top"
                                title="Tooltip on top">
                                <i class="far fa-building fa-2x"></i>
                        </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
<div>Have Questions? Contact us! {{ email|urlize }}</div>

{% endblock %}

courses/templates/courses/course_nav.html
{% for course in courses %}
    <div> <a href="{% url 'courses:detail' pk=course.id %}">{{ course.title }}</a> </div>
{% endfor %}

courses/templates/courses/question_form.html
{%  extends "layout.html" %}
{% load course_extras %}
{% load static from staticfiles %}
{% block static %}

<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}

{% block title %} {{form.instance.prompt|default:"New Question" }} | {{ quiz.course.title }}{{block.super}}
{% endblock %}



{% block content %}
<div class="container question-form-container">
    <a class="breadcrumbs" href="{% url 'courses:detail' pk=quiz.course.pk %}">
        <h6><i class="fas fa-angle-left"></i> {{ quiz.course.title }} /</h6>
    </a>

    <a class="breadcrumbs" href="{% url 'courses:quiz' course_pk=quiz.course.pk step_pk=quiz.pk%}">
        <h6>{{ quiz.title }}</h6>
    </a>
    <div class=" container question-form-content">
        <div>
            <h6><i class="far fa-hand-point-down"></i> {{ form.instance.prompt|default:"Make a new question"}} :</h6>
            <form action="" method="POST">
                {% csrf_token %}
                <div><label class="question-labels" for="{{ form.prompt.id_for_label }}">Prompt</label>
                    {{ form.prompt }}</div>
                <div><label class="question-labels" for="{{ form.order.id_for_label }}">Order</label>
                    {{ form.order }}</div>

                <div class="table-responsive z-depth-1">
                    <table class="table ">
                        <thead class="grey lighten-2">
                            <tr>
                                <th scope="col">Order</th>
                                <th scope="col">Text</th>
                                <th scope="col">Correct?</th>
                                <th scope="col">Delete?</th>
                            </tr>
                        </thead>
                        {{ formset.management_form }}
                        <tbody class="order">
                            {% for form in formset %}
                            <tr {% if form.instance.pk %} item {% else %} new {% endif %}>
                                <td> {{ form.id }} {{ form.order }}</td>
                                <td> {{ form.text }} </td>
                                <td> {{ form.correct }} </td>
                                {%  if form.instance.pk %}
                                <td> {{ form.DELETE }} </td>
                                {% else %}
                                <td></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <input type="submit" value="save" class="btn btn-outline-blue-grey waves-effect save">
            </form>
        </div>
    </div>

</div>
{% endblock %}

courses/templates/courses/quiz_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}
{% block static %}

<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}
{% block content %}

<div class="container quiz-detail-container">
    <a href="{% url 'courses:detail' pk=step.course.pk%}">
        <h6><i class="fas fa-angle-left"></i> {{ step.course.title }} /</h6>
    </a>
    <div class="container quiz-detail-content-container z-depth-1 rounded">
        <div class="quiz-detail-content">
                <h6 id="call-to-action"><i class="far fa-hand-point-down"></i> {{ step.title }} : </h6>
            {% for question in step.question_set.all %}
            <ul>
                <li>
                    <p>{{ question.prompt }}</p>
                    {% for answer in question.answer_set.all %}
                    <ul>
                        <li>{{answer.text}}</li>
                    </ul>
                    {% endfor %}

                    <a id="edit-question" href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}"><i class="far fa-edit fa-sm"> <small>Edit Question</small></i></a>

                </li>
            </ul>

            {% endfor %}
        </div>

    </div>
    <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='mc'%}"><button class="btn btn-outline-blue-grey waves-effect"> <i class="far fa-plus-square"></i>  New Multiple Choice
        Question</button></a>
<a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='tf'%}"><button class="btn btn-outline-blue-grey waves-effect"><i class="far fa-plus-square"></i>  New True/False
        Question</button></a>
    <a href="{% url 'courses:edit_quiz' course_pk=step.course.pk quiz_pk=step.pk %}"><button class="btn btn-outline-blue-grey waves-effect"><i class="fas fa-pen-alt"></i> Edit</button></a>
</div>

{% endblock %}

courses/templates/courses/quiz_form.html
{% extends "layout.html" %}
{% load course_extras %}
{% load static from staticfiles %}
{% block title %} {{form.instance.title|default:"New Quiz"}} | {{course.title}} {{ block.super }} {% endblock %}
{% block static %}

<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}
{% block content %}
<div class="container quiz-form">
        <form action="" method="POST">
            <h3>{{form.instance.title|default:"-Make a New Quiz-"}}</h3>
            {% csrf_token %}
            <div><label class="quiz-labels" for="{{ form.title.id_for_label }}">Title</label>
                {{ form.title }}</div>
            <div><label class="quiz-labels" for="{{ form.description.id_for_label }}">Description</label>
                {{ form.description }}</div>
            
            <div><label class="quiz-labels" for="{{ form.total_questions.id_for_label }}">No. of Questions</label>
                {{ form.total_questions }}</div>
            <div><label class="quiz-labels" for="{{ form.order.id_for_label }}">Order</label>
                {{ form.order }}</div>
            <button type="submit" class="btn btn-outline-blue-grey waves-effect"><span id="save">Save</span></button>

        </form>
        
</div>

{% endblock %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}

{% block content %}
<article>
    <a href="{% url 'courses:detail' pk=step.course.pk%}">{{ step.course.title }}</a> 
    <h3> {{ step.title }} </h3>
    {% with con=step.content %}
        {{ con|linebreaks }} content: {{ con|wordcount }} words.
    {% endwith %}
</article>
{% endblock %}

courses/templates/courses/text_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}
{% block static %}

<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}
{% block content %}
<div class="container text-detail-container">
        <h1><a href="{% url 'courses:detail' pk=step.course.pk%}">{{ step.course.title }}</a></h1> 
        <h3> {{ step.title }} </h3>
         <p>{{ step.description }}</p>
         {% with con=step.content %}
        <p>{{ con|linebreaks }} </p>
        content: {{ con|wordcount }} words.
        {% endwith %} 
</div>
{% endblock %}