courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_detail, name='text'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail, name='quiz'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create, name='create_quiz'),
    url(r'(?P<course_pk>\d+)/edit_quiz(?P<quiz_pk>\d+)/$', views.quiz_edit, name='edit_quiz'),
    url(r'(?P<quiz_pk>\d+)/create_question(?P<question_type>mc|tf)/$', views.create_question, name='create_question'),
    url(r'(?P<quiz_pk>\d+)/edit_question(?P<question_pk>\d+)/$', views.edit_question, name='edit_question'),
    url(r'(?P<question_pk>\d+)/create_answer/$', views.answer_form, name='create_answer'),
    url(r'by/(?P<teacher>[-\w]+)/$', views.courses_by_teacher, name='by_teacher'),
    url(r'search/$', views.search, name='search'), 
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^api/v1/courses', include('courses.api_urls', namespace='courses_api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^suggest/$', views.suggestion_view, name='suggestion'),
    url(r'^$', views.home_page, name='home'),
    url(r'^about-us$', views.aboutus_view, name='about_us'),
    url(r'^blog$', views.blog_view, name='blog'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += staticfiles_urlpatterns()

templates/about.html
{% extends "layout.html" %}

{% block content %}
<div class="about-us-page-intro-wrapper">
        <div class="container-fluid about-us-page-intro">
                <img class="about-us-page-intro-image"
                        src="https://images.unsplash.com/photo-1537202108838-e7072bad1927?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1600"
                        alt="">
                <div class="about-us-page-container">
                        <h3>-Our Mission-</h3>
                        <p>Ensure better education for a better world</p>
        
                        <h4>About</h4>
        
                        <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                                oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                                propriae cum id, no vim cotidieque repudiandae mediocritatem.
        
                                Pro ex saepe malorum persecuti. Definiebas referrentur eu sed, sed ex erant doctus, nobis
                                suscipit apeirian ei nam. Saepe animal te vel, decore recteque partiendo ius ad, vel fierent
                                lucilius at. Diam atomorum suavitate ad pro. Te pro viderer tamquam persecuti, no dissentiet
                                conclusionemque nec, mei te nihil animal.</p>
                        <div class="row about-us-page-row">
                        <div class="col-md-6">
                                <h6>Partners</h6>
                                <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                                        oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                                        propriae cum id, no vim cotidieque repudiandae mediocritatem.</p>
                        </div>
                        <div class="col-md-6">
                                <h6>Graduates</h6>
                                <p>Pro ex saepe malorum persecuti. Definiebas referrentur eu sed, sed ex erant doctus, nobis
                                        suscipit apeirian ei nam. Saepe animal te vel, decore recteque partiendo ius ad, vel fierent
                                        lucilius at. Diam atomorum suavitate ad pro. Te pro viderer tamquam persecuti, no dissentiet
                                        conclusionemque nec, mei te nihil animal</p>
                        </div>
                        </div>
                        <div class="row about-us-page-row">
                        <div class="col-md-6">
                                <h6>Badges awarded</h6>
                                <p>Pro ex saepe malorum persecuti. Definiebas referrentur eu sed, sed ex erant doctus, nobis
                                        suscipit apeirian ei nam. Saepe animal te vel, decore recteque partiendo ius ad, vel fierent
                                        lucilius at. Diam atomorum suavitate ad pro. Te pro viderer tamquam persecuti, no dissentiet
                                        conclusionemque nec, mei te nihil animal</p>
                        </div>
                        <div class="col-md-6">
                                <h6>Premises</h6>
                                <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                                        oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                                        propriae cum id, no vim cotidieque repudiandae mediocritatem.</p>
                        </div>
                        </div>
                        
                </div>
        </div>
        
</div>
{% endblock %}
{% block script%}

{% endblock %}

templates/blog.html
{% extends "layout.html" %}

{% block content %}
<!-- <div class="container-fluid mask">
    <img class="mask-img" src="static/images/landingpageintroimg.jpg" alt="">
</div> -->
<div class="container blog-container">
    <h4 class="blog-h4">This is the title of your first post</h4>
    <div class="row blog-row">
        <div class="col-md-6 blog-img-div">
            <img class="blog-img" src="https://images.unsplash.com/photo-1501504905252-473c47e087f8" alt="">
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                propriae cum id, no vim cotidieque repudiandae mediocritatem.</p>
        </div>
    </div>
    <h4 class="blog-h4">This is the title of your second post</h4>
    <div class="row blog-row">
        <div class="col-md-6 blog-img-div">
            <img class="blog-img" src="https://images.unsplash.com/photo-1505330622279-bf7d7fc918f4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=350&q=220" alt="">
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                propriae cum id, no vim cotidieque repudiandae mediocritatem.</p>
        </div>
    </div>
    <h4 class="blog-h4">This is the title of your third post</h4>
    <div class="row blog-row">    
        <div class="col-md-6 blog-img-div">
            <img class="blog-img" src="https://images.unsplash.com/photo-1457369804613-52c61a468e7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=350&q=220" alt="">
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                propriae cum id, no vim cotidieque repudiandae mediocritatem.</p>
        </div>
    </div>
    <h4 class="blog-h4">This is the title of your fourth post</h4>
    <div class="row blog-row">   
        <div class="col-md-6 blog-img-div">
            <img class="blog-img" src="https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=350&q=220" alt="">
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                propriae cum id, no vim cotidieque repudiandae mediocritatem.</p>
        </div>
    </div>
    <h4 class="blog-h4">This is the title of your fifth post</h4>
    <div class="row blog-row">    
        <div class="col-md-6 blog-img-div">
            <img class="blog-img" src="https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=350&q=220" alt="">
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, quaeque albucius sed ex. Essent utamur repudiandae sea cu, vocent
                oportere ei mea. In sint timeam neglegentur vel, eam error fabellas et, eum quem eius no. Vitae
                propriae cum id, no vim cotidieque repudiandae mediocritatem.</p>
        </div>
    </div>

</div>

</div>
{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title%} Home Page {%endblock%}

{% block content %}
<div class="container-fluid" id="landing-page-intro">
    <img id="landing-page-intro-img" src="static/images/john-schnobrich-520023-unsplash.jpg" alt=""
        class="img-responsive">
    <div id="landing-page-intro-text">
        <!-- <p>Dont miss our latest course, {% newest_course %}!</p> -->
        <div class="landing-page-intro-content" id="intro-animate">
            <h1>WE ENSURE BETTER EDUCATION
                FOR A BETTER WORLD</h1>
            <p>It is a long established fact that a reader will be distracted by the readable content of a
                page when looking at its layout</p>
            <a href="{% url 'courses:list' %}"><button>Click here to view all courses</button></a>
        </div>
    </div>
</div>
<div class="container" id="single-feature-container">
    <div class="row" id="single-feature-row">
        <div class="col-md-4">
            <div class="single-feature">
                <div class="single-feature-title">
                    <h4>The standard Lorem</h4>
                </div>
                <div class="single-feature-description">
                    <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has
                        roots in a piece of classical Latin literature from 45 BC, making it
                        over 2000 years old.</p>
                    <a href="">join now</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="single-feature">
                <div class="single-feature-title">
                    <h4>The standard Lorem</h4>
                </div>
                <div class="single-feature-description">
                    <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has
                        roots in a piece of classical Latin literature from 45 BC, making it
                        over 2000 years old.</p>
                    <a href="">join now</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="single-feature">
                <div class="single-feature-title">
                    <h4>The standard Lorem</h4>
                </div>
                <div class="single-feature-description">
                    <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has
                        roots in a piece of classical Latin literature from 45 BC, making it
                        over 2000 years old.</p>
                    <a href="">join now</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid" id="popular-courses-container">
    <div class="row" id="popular-courses-call-to-action">
        <div>
            <h4>Popular Courses we offer</h4>
            <p>Some text can be added here</p>
        </div>
    </div>
    <div class="row" id="popular-courses-slider">
        <div class="col-md-3 col-lg-3" id="popular-course-div">
            <div class="popular-course">
                <img src="https://www.hindilearn.in/images1/javascript.png" alt="">
            </div>
            <div class="popular-course-description">
                <h6>Learn Java Script</h6>
                <p>Some text describing the course here</p>
            </div>
        </div>

        <div class="col-md-3 col-lg-3">
            <div class="popular-course">
                <img src="https://www.thoughtco.com/thmb/W8mZRP83ZBl7QeKAJuMajXZjux0=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/2000px-Python.svg-56a7b0bc5f9b58b7d0ecea1f.jpg" alt="">
            </div>
            <div class="popular-course-description">
                <h6>Learn-Python</h6>
                <p>Some text describing the course here</p>
            </div>
        </div>

        <div class="col-md-3 col-lg-3">
            <div class="popular-course">
                <img src="https://process.filestackapi.com/cache=expiry:max/resize=width:1050/compress/BLF55V9jSCuZ50iFD1UJ" alt="">
            </div>
            <div class="popular-course-description">
                <h6>Learn Angular</h6>
                <p>Some text describing the course here</p>
            </div>
        </div>

        <div class="col-md-3 col-lg-3" >
            <div class="popular-course">
                <img src="https://cdn-images-1.medium.com/max/1200/1*1OBwwxzJksMv0YDD-XmyBw.png" alt="">
            </div>
            <div class="popular-course-description">
                <h6>Learn Django</h6>
                <p>Some text describing the course here</p>
            </div>
        </div>


    </div>
</div>
<!-- <div id="parallax-container">
    <div id="parallax">
            <h1>Parallax Effect</h1>
            <p>Pure Css //No javascript</p>
    </div>
</div> -->
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load course_extras %}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %} {% endblock %} </title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  {% block static %}{% endblock %}
</head>

<body>
  <header id="header-with-navbar">

    <div class="header-top">
      <div class="container" id="top-nav-container">
        <div class="row" id="top-nav-row">
          <div class="col-lg-6 col-sm-6 col-6" id="social-network-icons-layout-page">
            <a><i class="fab fa-facebook-f ml-0 fa-xs"></i></a>
            <a><i class="fab fa-twitter ml-3 fa-xs"></i></a>
            <a><i class="fab fa-instagram ml-3 fa-xs"></i></a>
            <a><i class="fab fa-linkedin-in ml-3  fa-xs"></i></a>
          </div>
          <div class="col-lg-6 col-sm-6 col-4" id="contact-icons-layout-page">
            <a href="mailto:dmontetproff@gmail.com">dmontetproff@gmail.com</a>
            <a href="tel:254702644342" class="ml-2 mobile">+254 702 644 342</a>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid" id="navbar-container">
      <div id="navbar-row">
          <nav class="navbar navbar-expand-lg">
              <a id="logo-anchor-tag" href="{% url 'home' %}"><img id="logo" src="{% static 'images/logo_transparent (3).png' %}" alt="Africode"></a>               
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="basicExampleNav">
                <ul class="navbar-nav mr-auto">
                  <!-- <form action="{% url 'courses:search' %}" method="GET">
                      <li class="nav-item">
                          <input type="search" name="q">
                      </li>
                      <button class="secondary small" type="submit">Search</button>
                  </form> -->
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home
                    </a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'about_us' %}">About
                      </a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                      aria-expanded="false" href="{% url 'courses:list' %}">Courses
                    </a>
                    <div class="dropdown-menu dropdown-primary" id="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                     {% nav_courses_list %}
                     <a href="{% url 'courses:list' %}">see all</a>
                    </div>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog' %}">Blog
                        <span class="sr-only"></span>
                      </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                  </li>
        
                </ul>
              </div>
          </nav>
      </div>
    </div>


  </header>


  {% if messages %}
  <div>
    <div>
      {% for message in messages %}
      {{ message }}
      {% endfor %}
    </div>
  </div>
  {% endif %}

  <div class="container-fluid" id="body-block-content">
    {% block content %}
    {% endblock %}
  </div>

  <footer class="page-footer font-small pt-4">
    <div class="container text-center text-md-left">
      <div class="row text-center text-md-left mt-3 pb-3">
        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Africode</h6>
          <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
            consectetur
            adipisicing elit.</p>
        </div>
        <!-- Grid column -->
  
        <hr class="w-100 clearfix d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
          <p>
            <a href="#!">MDBootstrap</a>
          </p>
          <p>
            <a href="#!">MDWordPress</a>
          </p>
          <p>
            <a href="#!">BrandFlow</a>
          </p>
          <p>
            <a href="#!">Bootstrap Angular</a>
          </p>
        </div>
        <!-- Grid column -->
  
        <hr class="w-100 clearfix d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
          <p>
            <a href="#!">Your Account</a>
          </p>
          <p>
            <a href="#!">Become an Affiliate</a>
          </p>
          <p>
            <a href="#!">Shipping Rates</a>
          </p>
          <p>
            <a href="#!">Help</a>
          </p>
        </div>
  
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
          <p>
            <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope mr-3"></i> dmontetproff@gmail.com</p>
          <p>
            <i class="fas fa-phone mr-3"></i> + 254 702 644 342</p>
          <p>
            <i class="fas fa-print mr-3"></i> + 254 734 560 629</p>
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Footer links -->
  
      <hr>
  
      <!-- Grid row -->
      <div class="row d-flex align-items-center">
  
        <!-- Grid column -->
        <div class="col-md-7 col-lg-8">
  
          <!--Copyright-->
          <p class="text-center text-md-left">© 2018 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/">
              <strong> MDBootstrap.com</strong>
            </a>
          </p>
  
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-5 col-lg-4 ml-lg-0">
  
          <!-- Social buttons -->
          <div class="text-center text-md-right">
            <ul class="list-unstyled list-inline">
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-google-plus-g"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
</footer>



  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js">
  </script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"></script>
  <script src="{% static 'scripts/layout.js' %}"></script>
  {% block script %}
  {% endblock %}
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="basicExampleNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'views.home_page' %}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:list' %}">Courses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>

    <form class="form-inline">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      </div>
    </form>
  </div>
  <!-- Collapsible content -->

</nav>

templates/suggestion_form.html
{% extends "layout.html" %}

{% block title%} Suggest an idea! {%endblock%}

{% block content %}
    
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit">
        </form>

{% endblock %}